### ISSUE TITLE
another poorly documented ware

### ISSUE THREAD

**Issue by dimyme** [libratbag/piper#283] opened 2018-12-31 21:45 UTC
without a mouse, one never knows WTF the app is even about.

So the programmers have not thought about the very first things.

**Comment by Dragon8oy** [comment] 2018-12-31 22:13
Have you ever read the readme?

**Comment by Hjdskes** [comment] 2019-01-01 00:20
I'm inclined to close this as trolling. You get one chance to explain what the problem is exactly, because I don't understand your point. Without a (gaming) mouse, you don't need Piper. Problem solved?

**Comment by whot** [comment] 2019-01-01 23:06
closing, this is not an acceptable way of interacting with developers of free software.

**Closed by whot** 2019-01-01 23:06 UTC
