### ISSUE TITLE
Add option to disable mouse buttons

### ISSUE THREAD

**Issue by Ustin** [libratbag/piper#718] opened 2022-01-19 13:32 UTC
My mouse have additional "forward/back" buttons I sometimes press accidentaly. 

I do not need these buttons and I would like to disable them completely. 

Windows software provided by manufacturer is able to do it, but piper misses this option. 

I can remap them to one of less intrusive function like sideways scrolling, but I can't set it "do nothing when I press this button". 

So, my request is to add "nothing" option to mouse button function selection.

**Comment by staticssleever668** [comment] 2023-03-24 11:37
Duplicate of #247, fixed by #849.

**Closed by staticssleever668** 2023-03-24 11:37 UTC
Labels: enhancement
