### ISSUE TITLE
Option to set button to 'none'

### ISSUE THREAD

**Issue by alcomposer** [libratbag/piper#799] opened 2022-10-15 03:01 UTC
My G502 Hero has scroll buttons left & right.

These buttons are quite annoying for canvas based interactions. For example - in Gimp, or Godot / Blender node editor.

The left/right buttons can activate when I click scrollwheel down, and zoom in/out without me wanting to.

I would like to set switch off these buttons, but there is no 'none' option in the interaction chooser.

When I set an empty custom macro Piper is unable to set the mouse to that empty macro.

I think a `none` option would be useful for users to be able to deactivate certain buttons.
![Screenshot from 2022-10-15 13-26-39](https://user-images.githubusercontent.com/12004932/195966046-87a8e8ae-745b-4e67-b3dd-250f91b0c915.png)

**Comment by staticssleever668** [comment] 2022-10-15 09:37
Duplicate of #498.

**Closed by staticssleever668** 2022-10-15 09:37 UTC
Labels: enhancement
