### ISSUE TITLE
Keyboard ShortCuts not working Arch Linux

### ISSUE THREAD

**Issue by baxterchippy** [libratbag/piper#690] opened 2021-11-02 23:34 UTC
I tried setting a keyboard shortcut to any of the buttons G6-G9 and it doesnt work. I have a Logitech G640. Any help would be appreciated. I can set say G6 to a left button click, but setting it to a keyboard shortcut does not work. I wanted to set it to Super Key F to open Firefox.

**Comment by xmarkclx** [comment] 2021-11-15 13:19
Same.

**Comment by Rukaparashavsyavselennayanasha** [comment] 2022-01-06 17:04
Same.

**Comment by staticssleever668** [comment] 2023-03-24 12:11
> I tried setting a keyboard shortcut to any of the buttons G6-G9 and it doesnt work.

Please, reopen the issue following the suggested issue template.

> I wanted to set it to Super Key F to open Firefox.

This part seems like a duplicate of #618.

**Closed by staticssleever668** 2023-03-24 12:11 UTC
