### ISSUE TITLE
Please add support for mapping Logitech G915 keyboard macro keys with gui

### ISSUE THREAD

**Issue by Wolf-lbh** [libratbag/piper#714] opened 2022-01-12 02:31 UTC
**Is your feature request related to a problem? Please describe.**
I understand Piper is just a frontend for ratbagd DBus daemon however ratbagd supports the g915 both 10 keyless and full keyboard models and it has 5 macro keys I would really like to be able to configure on linux.

**Describe the solution you'd like**
Please allow the G915 keyboard to have macro keys mapped via Piper's gui.

**Describe alternatives you've considered**
The only other way to use the G915s macros on Linux would be to map them on a windows computer or in a windows vm and reconnect it to that computer/vm every time I wanted to change my macros and then save them to onboard memory. This solution is really inconvenient and I would drastically prefer not doing it.

**Additional context**
N/A

**Comment by Techognito** [comment] 2023-02-22 10:04
This seems to be the same as issue #605

**Comment by staticssleever668** [comment] 2023-02-22 13:49
If I understand correctly, this is saying that not all keys are shown in Piper, although they are present when using ratbagctl. This was probably caused by a missing graphics for the device, while the default placeholder image only shows up to 8 keys. If so, this has been fixed in #578 (available in Piper v0.6 and higher).

**Closed by staticssleever668** 2023-02-22 13:49 UTC
Labels: enhancement

**Comment by Techognito** [comment] 2023-02-22 14:56
Well, the keys are shown in piper (atleast as of v0.7) but when trying to change key 1 or 2 it detects as mouse instead of keyboard

![image](https://user-images.githubusercontent.com/74787545/220659676-4142e806-3c40-4a54-a428-ef97b83f631e.png)

when editing G1 or G2:
![image](https://user-images.githubusercontent.com/74787545/220659706-fbecaf37-bc2f-4448-b68b-f8c1e95083a6.png)

When editing G3,G4 or G5
![image](https://user-images.githubusercontent.com/74787545/220660114-ce02d5ce-b598-4939-9913-806d50d97c4a.png)

**Comment by Techognito** [comment] 2023-02-22 15:02
Button IDs according to the edit menu (in case this helps) :
![image](https://user-images.githubusercontent.com/74787545/220661568-ecd1a049-abe8-44fd-b680-a4b58f97808d.png)

**Comment by staticssleever668** [comment] 2023-02-22 15:22
> when trying to change key 1 or 2 it detects as mouse instead of keyboard

This has been fixed by #536, which was merged only recently, so it's not in a release yet. This won't be an issue once a new version of Piper comes out. :)
