### ISSUE TITLE
Application does not launch after installation

### ISSUE THREAD

**Issue by Brainiarc7** [libratbag/piper#107] opened 2017-08-13 14:31 UTC
Hello,

After building the package and launching it, this is what I get:

`$piper`

```
Traceback (most recent call last):
  File "/usr/bin/piper", line 32, in <module>
    from piper.application import Application
ImportError: No module named 'piper.application'; 'piper' is not a package

```
How can I fix this?

**Comment by Hjdskes** [comment] 2017-08-13 17:41
Are you by any chance on an APT-based distribution (Ubuntu, Debian, Linux Mint...)? If so, read https://github.com/libratbag/piper/issues/66.

Otherwise, please give us `build/meson-logs/install-log.txt` and the output of [this command](https://github.com/libratbag/piper/issues/66#issuecomment-318987001).

**Comment by Brainiarc7** [comment] 2017-08-14 19:04
Yes, I'm on an apt-based distribution, Ubuntu 16.04LTS.

Let me follow up with the issue highlighted above.

**Comment by whot** [comment] 2017-08-14 23:26
closing as dupe of #66 for now

**Closed by whot** 2017-08-14 23:26 UTC
