### ISSUE TITLE
Show unchangeable report rate

### ISSUE THREAD

**Issue by hadess** [libratbag/piper#834] opened 2023-02-03 16:10 UTC
Logitech Signature M650 mouse shows a changeable report rate:

![image](https://user-images.githubusercontent.com/769861/216649844-9cc1ab06-7e16-4cf2-bfb4-082ef14978a9.png)

Even though it isn't listed as a feature in the `ratbagctl` output:
```
$ ratbagctl thundering-gerbil info
thundering-gerbil - Logi M650
             Model: bluetooth:046d:b02a:0
 Number of Buttons: 6
    Number of Leds: 0
Number of Profiles: 1
Profile 0: (active)
  Name: n/a
  Resolutions:
    0: 1000dpi (active)
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 3'
  Button: 3 is mapped to 'button 4'
  Button: 4 is mapped to 'button 5'
  Button: 5 is mapped to none
```

 Even more bonkers is that if I try to change it, I get an error, and report rate appears in the info output:
```
$ ratbagctl thundering-gerbil info
thundering-gerbil - Logi M650
             Model: bluetooth:046d:b02a:0
 Number of Buttons: 6
    Number of Leds: 0
Number of Profiles: 1
Profile 0: (active)
  Name: n/a
  Report Rate: 500Hz
  Resolutions:
    0: 1000dpi (active)
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 3'
  Button: 3 is mapped to 'button 4'
  Button: 4 is mapped to 'button 5'
  Button: 5 is mapped to none
```

Using libratbag and piper from current git, with this definition added for the mouse:
```
$ cat data/devices/logitech-Signature-M650.device
[Device]
Name=Logitech Signature M650
DeviceMatch=bluetooth:046d:b02a
Driver=hidpp20
```

`solaar show` doesn't show the mouse as having the 8060 report rate feature.

I think it's possible that Piper assumes that any mouse with changeable DPI has variable report rate, and `ratbagd` doesn't check whether the functionality exists before trying to apply it:
```
ratbag error: hidpp20: failed to update report rate (-95)
ratbagd error: error committing device (-1000)
```

**Comment by staticssleever668** [comment] 2023-02-03 16:29
Could you post the output of `ratbagctl Logi rate get-all` while running ratbagd though `ratbagd --verbose=raw`, then change the report rate in Piper, and post the output of ratbagd?

**Comment by hadess** [comment] 2023-02-03 16:54
This isn't easily feasible, I have too many Logitech devices attached right now as I'm working on the HID++ driver in the kernel.

A single report rate is exported by ratbagd:
```
$ gdbus introspect --system --dest org.freedesktop.ratbag1 --object-path /org/freedesktop/ratbag1/profile/hidraw4/p0
node /org/freedesktop/ratbag1/profile/hidraw4/p0 {
[...]
  interface org.freedesktop.ratbag1.Profile {
    methods:
      SetActive(out u arg_0);
    signals:
    properties:
      readwrite s Name = '';
      readwrite b Disabled = false;
      @org.freedesktop.DBus.Property.EmitsChangedSignal("const")
      readonly u Index = 0;
      @org.freedesktop.DBus.Property.EmitsChangedSignal("const")
      readonly au Capabilities = [];
      @org.freedesktop.DBus.Property.EmitsChangedSignal("false")
      readonly ao Resolutions = ['/org/freedesktop/ratbag1/resolution/hidraw4/p0/r0'];
      @org.freedesktop.DBus.Property.EmitsChangedSignal("false")
      readonly ao Buttons = ['/org/freedesktop/ratbag1/button/hidraw4/p0/b0', '/org/freedesktop/ratbag1/button/hidraw4/p0/b1', '/org/freedesktop/ratbag1/button/hidraw4/p0/b2', '/org/freedesktop/ratbag1/button/hidraw4/p0/b3', '/org/freedesktop/ratbag1/button/hidraw4/p0/b4', '/org/freedesktop/ratbag1/button/hidraw4/p0/b5'];
      @org.freedesktop.DBus.Property.EmitsChangedSignal("false")
      readonly ao Leds = [];
      readonly b IsActive = true;
      readwrite u ReportRate = 0;
      @org.freedesktop.DBus.Property.EmitsChangedSignal("const")
      readonly au ReportRates = [500];
  };
};
```

**Comment by staticssleever668** [comment] 2023-02-22 14:19
libratbag populating ReportRates list even though changing report rates is not supported is a different thing, but could you try if #838 fixes the problem on Piper side?

**Comment by staticssleever668** [comment] 2023-02-22 14:25
Actually never mind, this bug is completely on libratbag side, my fix is incorrect.

**Closed** 2023-03-03 11:59 UTC
Labels: bug

**Comment by staticssleever668** [comment] 2023-03-03 12:03
The above disables report rate selection in Piper if ratbagd says it's unsupported, however, you can still trick ratbagd into thinking it does support it by setting `ReportRate` through ratbagctl to something other than `0`. After that if you launch Piper, it will happily show you report rate selection until ratbagd is restarted. So, the issue is not completely gone in this sense.
