### ISSUE TITLE
G502 X

### ISSUE THREAD

**Issue by sekasorto93** [libratbag/piper#946] opened 2024-02-29 12:27 UTC
Hey there. I have a Logitech G502 X. I'm wanting to use libratbag/piper with it, however when I use the piper GUI the image of the mouse is of the Libratbag/Piper mouse. I have the configuration file loaded and all device ID's match correctly. Is there something I might be doing incorrectly or perhaps work in development still for this? 

I also have the older G502 Hero mouse, this one is working correctly. ![image](https://github.com/libratbag/piper/assets/161720402/8e0fe674-cd66-48c3-a60b-fa724b8805f0)

**Comment by staticssleever668** [comment] 2024-02-29 17:35
Hi! The image was added in the master branch, Piper just hasn't seen a release in a while.
Duplicate of #919.

**Closed by staticssleever668** 2024-02-29 17:35 UTC

**Comment by sekasorto93** [comment] 2024-03-01 04:33
Thanks for that. Reinstalled from AUR, functions correctly now! 

One small issue I have found however, is binding SHIFT to G5 on the mouse. Appears to bind, but will not function as shift - rather it works as CTRL. 

Have you come across this before? 

![61fjq9eujBL _AC_SL1500_](https://github.com/libratbag/piper/assets/161720402/0d1a8aa6-75b2-4472-8aa2-c16fc14ccb65)
