### ISSUE TITLE
Macros that include mouse clicks(?)

### ISSUE THREAD

**Issue by tiritto** [libratbag/piper#802] opened 2022-11-11 09:43 UTC
I want to bing macro my mouse button so it sends a few keystrokes and then presses a button, for example A->B->Left Click. Im using Logitech G502 mouse, and as far as I know Logitech's native app on Windows does provide such functionality when creating macros. I'm not sure if such feature already exists in Piper or not, but if it does I just can't figure out how to access it.

**Comment by hooliowobbits** [comment] 2022-11-16 22:54
Hi there, i had the same issue awhile ago.  What i ended up doing was using https://github.com/dajusc/Linux-Mouse-Keybinds.  This allows you to bind mouse buttons key presses or combinations thereof (macros).  Basically it runs as a python process separate to your game, listens to mouse events and fires extra key presses into the game window.  Works with Proton OK.

**Comment by staticssleever668** [comment] 2023-03-08 17:18
Note: you can set it with ratbagctl if our driver for your mouse supports it.
(Although it will raise a Python `KeyError` right now if your try to print device data after that).

Example:
`ratbagctl Glorious button 5 action set macro BTN_LEFT`
(replace `Glorious` with the name of your device in `ratbagctl list`)

Closing this as duplicate of #782.

**Closed by staticssleever668** 2023-03-08 17:18 UTC
Labels: enhancement
