### ISSUE TITLE
Steelseries Rival 600 not detected by Piper on MX Linux KDE

### ISSUE THREAD

**Issue by BevanFindlay** [libratbag/piper#937] opened 2024-01-27 20:17 UTC
**Information**

- `ratbagd` version (`ratbagd --version`): 0.17
- Piper version: 0.7-1
- Distribution: MX Linux
- Device: Steelseries Rival 600
- Kernel version (ex. `uname -srmo`): Linux 6.6.11-1-liquorix-amd64 x86_64 GNU/Linux

**Describe the bug**
Unable to get Piper to detect my mouse: ratbagd seems to detect it ok (see logs below) and has the device file for it, but Piper says "Cannot find any devices - Please make sure your device is supported and plugged in".  ratbagctl also reports "No devices available."

**To Reproduce**
Installed from repo (i.e. apt install ratbagd; apt install piper), ensured ratbagd is running, tried to open Piper.

**Logs**
Please start the daemon with verbosity and reproduce the issue.

$ ratbagd --verbose=raw
Initializing libratbag
ratbag debug: New device: SteelSeries SteelSeries Rival 600
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver steelseries
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1724
ratbag debug: SteelSeries SteelSeries Rival 600 is device '/dev/hidraw2'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1724
ratbag debug: SteelSeries SteelSeries Rival 600 is device '/dev/hidraw3'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1724
ratbag debug: SteelSeries SteelSeries Rival 600 is device '/dev/hidraw4'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 01
ratbag debug: - HID report ID 02
ratbag debug: New device: SteelSeries SteelSeries Rival 600
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver steelseries
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1724
ratbag debug: SteelSeries SteelSeries Rival 600 is device '/dev/hidraw2'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1724
ratbag debug: SteelSeries SteelSeries Rival 600 is device '/dev/hidraw3'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1724
ratbag debug: SteelSeries SteelSeries Rival 600 is device '/dev/hidraw4'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 01
ratbag debug: - HID report ID 02
ratbag debug: New device: SteelSeries SteelSeries Rival 600
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver steelseries
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1724
ratbag debug: SteelSeries SteelSeries Rival 600 is device '/dev/hidraw2'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1724
ratbag debug: SteelSeries SteelSeries Rival 600 is device '/dev/hidraw3'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1724
ratbag debug: SteelSeries SteelSeries Rival 600 is device '/dev/hidraw4'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 01
ratbag debug: - HID report ID 02
ratbag debug: New device: NXP SEMICOND  LPC11Uxx USB HID
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 195d:2036
ratbag debug: New device: NXP SEMICOND  LPC11Uxx USB HID
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 195d:2036
ratbag debug: New device: NXP SEMICOND  LPC11Uxx USB HID
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 195d:2036
ratbag debug: New device: NXP SEMICOND  LPC11Uxx USB HID
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 195d:2036
ratbag debug: New device: NXP SEMICOND  LPC11Uxx USB HID
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 195d:2036
ratbag debug: New device: NXP SEMICOND  LPC11Uxx USB HID
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 195d:2036
ratbag debug: New device: NXP SEMICOND  LPC11Uxx USB HID
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 195d:2036
ratbag debug: New device: NXP SEMICOND  LPC11Uxx USB HID
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 195d:2036
ratbag debug: New device: ELAN Touchscreen
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 04f3:222a
ratbag debug: New device: ITE8350:00 048D:8350
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 048d:8350
ratbag debug: New device: MSFT0001:00 06CB:73FD
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 06cb:73fd
DBus server ready

**Additional context**

**Comment by staticssleever668** [comment] 2024-01-27 20:38
Hi! It's a regression since v0.16 and a duplicate of https://github.com/libratbag/libratbag/issues/1438, which was fixed in the master branch but is not in a release yet. For now to make the device work with libratbag, your only option is probably to build from source.

**Closed by staticssleever668** 2024-01-27 20:38 UTC
Labels: bug

**Comment by BevanFindlay** [comment] 2024-01-27 20:55
Tried building from source, but get the error:
meson.build:63:0: ERROR: Dependency "libudev" not found, tried pkgconfig and cmake
Any suggestions?

**Comment by BevanFindlay** [comment] 2024-01-27 21:44
Never mind, I eventually managed to work through the dependencies for ratbagd and piper and it worked.  Thanks
