### ISSUE TITLE
Doesn't find Logitech G pro wireless.

### ISSUE THREAD

**Issue by iLikePizzaRolls** [libratbag/piper#620] opened 2021-02-20 10:09 UTC
i'm using Logitech G pro wireless and it won't recognize it and it is in the supported mice list. 
![Screenshot 2021-02-20 at 12 11 07](https://user-images.githubusercontent.com/74143445/108592086-c72dcc00-7374-11eb-990b-9e3f897bf510.png)

**Comment by FFY00** [comment] 2021-02-20 18:22
Distribution? Linux version (`uname -a`)?

**Comment by iLikePizzaRolls** [comment] 2021-02-21 11:53
> Distribution? Linux version (`uname -a`)?

it says: Linux penguin 5.4.74-10576-gb6cc41974db3 #1 SMP PREEMPT Sun Nov 8 15:08:12 PST 2020 x86_64 GNU/Linux

**Comment by poligarpi** [comment] 2022-01-19 08:00
I have the same issue, only recognizes the mouse if it's wired.

uname -a 
                                                                                                                                                                                                                                                                                                    Linux JoseGamingPC 5.16.1 #1 SMP PREEMPT Wed Jan 19 00:08:04 CST 2022 x86_64 GNU/Linux

**Comment by seangenabe** [comment] 2022-01-19 08:07
Fwiw it works for me on a Powerplay.

**Comment by vdovhanych** [comment] 2022-02-15 23:49
Same for me on G Pro wireless superlight. It sees the mouse when connected with the cable but not while  wirelessly.

**Comment by rlka** [comment] 2022-03-02 14:51
Same for me.
Linux Home 4.15.0-169-generic #177-Ubuntu SMP Thu Feb 3 10:50:38 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by DivineBicycle** [comment] 2022-09-09 09:47
Also not working for me, ```Linux arch 5.19.7-zen2-1-zen #1 ZEN SMP PREEMPT_DYNAMIC```, on Arch Linux

**Comment by joshualeduc** [comment] 2023-04-25 22:21
Linux Deck 5.13.0-valve36-1-neptune #1 SMP PREEMPT Mon, 19 Dec 2022 23:39:41 +0000 x86_64 GNU/Linux

Same issue with a G Pro Wireless superlight using a steam deck. It appears in piper when connected through my usb cable, but will not appear when connected through the usb wireless adapter.

**Comment by staticssleever668** [comment] 2023-04-25 22:33
Since this completely depends on libratbag, closing this in favor of a libratbag issue: https://github.com/libratbag/libratbag/issues/1333
In short, the issue is that Linux doesn't support the c547 receiver (lightspeed?). I think I've seen a related Linux patch recently, so maybe this is going to get fixed in a few Linux release cycles.

**Closed by staticssleever668** 2023-04-25 22:33 UTC
