### ISSUE TITLE
ratbagd_device.model appears to return 'NoneType'

### ISSUE THREAD

**Issue by Nik--** [libratbag/piper#362] opened 2019-07-05 10:08 UTC
When I try to run piper after compiling, this error is thrown:

```
(piper:18453): Gtk-WARNING **: 13:01:51.913: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(piper:18453): Gtk-WARNING **: 13:01:51.913: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(piper:18453): Gtk-WARNING **: 13:01:51.913: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/piper/application.py", line 52, in do_activate
    window = Window(self._ratbag, application=self)
  File "/usr/lib64/python3.6/site-packages/piper/window.py", line 69, in __init__
    self._present_mouse_perspective(ratbag.devices[0])
  File "/usr/lib64/python3.6/site-packages/piper/window.py", line 147, in _present_mouse_perspective
    mouse_perspective.set_device(device)
  File "/usr/lib64/python3.6/site-packages/piper/mouseperspective.py", line 90, in set_device
    self.stack.add_titled(ResolutionsPage(device), "resolutions", _("Resolutions"))
  File "/usr/lib64/python3.6/site-packages/piper/resolutionspage.py", line 66, in __init__
    self._init_ui()
  File "/usr/lib64/python3.6/site-packages/piper/resolutionspage.py", line 71, in _init_ui
    mousemap = MouseMap("#Buttons", self._device, spacing=20, border_width=20)
  File "/usr/lib64/python3.6/site-packages/piper/mousemap.py", line 111, in __init__
    svg_bytes = get_svg(ratbagd_device.model)
  File "/usr/lib64/python3.6/site-packages/piper/svg.py", line 32, in get_svg
    if model.startswith('usb:') or model.startswith('bluetooth:'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

Also not sure if this is relevant info, but it might help you out. ratbagctl detects my mouse just normally:

```
nik-pc /var/db/repos/nik/app-misc/piper # ratbagctl info event3
event3 - Logitech USB Receiver
               SVG: logitech-g700.svg
      Capabilities: query-configuration, resolution, switchable-resolution, profile, switchable-profile, disable-profile, button, button-keys, button-macros
 Number of Buttons: 13
    Number of Leds: 0
Number of Profiles: 5
Profile 0: (active)
  Name : 'Profile 1'
  Resolutions:
    0: 850x850dpi @ 125Hz
    1: 1700x1700dpi @ 125Hz
    2: 2550x2550dpi @ 125Hz
    3: 3400x3400dpi @ 125Hz
    4: 6800x6800dpi @ 125Hz (active)
  Button: 0 type left is mapped to 'button 1'
  Button: 1 type middle is mapped to 'button 2'
  Button: 2 type right is mapped to 'button 3'
  Button: 3 type thumb is mapped to 'button 4'
  Button: 4 type thumb2 is mapped to 'button 5'
  Button: 5 type thumb3 is mapped to UNKNOWN
  Button: 6 type thumb4 is mapped to UNKNOWN
  Button: 7 type resolution-cycle-up is mapped to 'battery-level'
  Button: 8 type resolution-down is mapped to 'resolution-down'
  Button: 9 type resolution-up is mapped to 'resolution-up'
  Button: 10 type profile-cycle-up is mapped to 'profile-cycle-up'
  Button: 11 type wheel-left is mapped to 'wheel-left'
  Button: 12 type wheel-right is mapped to 'wheel-right'
Profile 1:
  Name : 'Profile 2'
  Resolutions:
    0: 850x850dpi @ 1000Hz
    1: 1700x1700dpi @ 1000Hz
    2: 2550x2550dpi @ 1000Hz
    3: 3400x3400dpi @ 1000Hz
    4: 6800x6800dpi @ 1000Hz (active) (default)
  Button: 0 type left is mapped to 'button 1'
  Button: 1 type middle is mapped to 'button 2'
  Button: 2 type right is mapped to 'button 3'
  Button: 3 type thumb is mapped to 'button 4'
  Button: 4 type thumb2 is mapped to 'button 5'
  Button: 5 type thumb3 is mapped to UNKNOWN
  Button: 6 type thumb4 is mapped to UNKNOWN
  Button: 7 type resolution-cycle-up is mapped to 'battery-level'
  Button: 8 type resolution-down is mapped to 'resolution-down'
  Button: 9 type resolution-up is mapped to 'resolution-up'
  Button: 10 type profile-cycle-up is mapped to 'profile-cycle-up'
  Button: 11 type wheel-left is mapped to UNKNOWN
  Button: 12 type wheel-right is mapped to UNKNOWN
Profile 2: (disabled)
Profile 3: (disabled)
Profile 4: (disabled)
```

**Comment by spectrapulse** [comment] 2019-07-06 19:04
Having the same issue with my G903.
Both over the wireless receiver and over wired.

Running Pop!_OS 19.04.

**Comment by Nik--** [comment] 2019-07-07 08:31
Issue is not present at piper release 0.2.903 and libratbag v0.9.903.

**Comment by Jakob-em** [comment] 2019-07-07 10:14
Have the same issue with my g502 lightspeed.

**Comment by whot** [comment] 2019-07-08 00:11
are you running against ratbagd 0.9.905? The model bits are hardcoded there, so there shouldn't be any case where this is NULL.

**Comment by Nik--** [comment] 2019-07-08 06:56
I've tried to run it against 0.9.905, but the problem there persists.

**Comment by whot** [comment] 2019-07-25 02:05
The ratbagd code to retrieve the Model is here: https://github.com/libratbag/libratbag/blob/master/ratbagd/ratbagd-device.c#L193. There's no path that returns None, so something weird is going on here. As you can tell by the lack of responses, we're seriously struggling to find time for libratbag, we'll need someone to debug this please.

**Comment by whot** [comment] 2019-07-25 02:55
Also, ftr, the line `               SVG: logitech-g700.svg` from the ratbagctl output was removed with 905 when the SVG handling switched to piper and was replaced with the `Model` property instead. So if your `ratbagctl` is still showing that, you're not on 905 or later.

**Comment by Nik--** [comment] 2019-07-27 09:14
Well to summarize the issue, with piper release 0.2.903 and libratbag v0.9.903 I had no issues. The issue started to appear after those versions. I am currently using piper release 0.2.905 and libratbag v0.9.906 and the problem does not persist there. It seems that whatever the issue was, it lived around those versions.

**Comment by whot** [comment] 2019-07-27 11:11
>  It seems that whatever the issue was, it lived around those versions.

libratbag 0.9.905 added the `Model` bit and removed the SVGs. piper 0.2.904 added those SVGs and became reliant on the `Model` bit. Any combination where one is less than those to numbers will fail.

Unfortunately, package management is terrible here. We have a warning during `meson.build` if ratbgad isn't compatible but once the package is built, you won't get that warning. So not sure what we can do here.

**Comment by Nik--** [comment] 2019-07-27 20:50
Well I'm currently running libratbag 0.9.906 and piper 0.2.905, its kinda confusing having such version difference, one will naturally assume both versions must fit. The good part is that there is no issue anymore, the bad part is that this might happen in the future with some other kind of incompatibility.

**Comment by whot** [comment] 2019-07-29 03:41
Workaround: https://github.com/libratbag/libratbag/pull/775

**Comment by whot** [comment] 2019-07-30 10:16
Closing this, it was caused by a version mismatch. There's the PR linked above to work around this, that's about all we can do right now.

**Closed by whot** 2019-07-30 10:16 UTC
