### ISSUE TITLE
Mouse Image bug

### ISSUE THREAD

**Issue by luccacondratiuk** [libratbag/piper#264] opened 2018-09-24 13:32 UTC
![captura de tela de 2018-09-24 10-29-09](https://user-images.githubusercontent.com/28022104/45954991-11b09000-bfe5-11e8-889c-b2d16c748371.png)

**Comment by Hjdskes** [comment] 2018-09-24 13:35
Duplicate of #233.

**Closed by Hjdskes** 2018-09-24 13:35 UTC
