### ISSUE TITLE
Piper as appimage?

### ISSUE THREAD

**Issue by Pshemas** [libratbag/piper#199] opened 2017-11-24 17:46 UTC
Is there any chance to see Piper released as .Appimage ? That would give us easy, cross platform build, without huge chunk of dependencies issues (as from what I understand Flatpak is not possible in this case atm).

I've thought about using Piper on my OpenSUSE Leap install - sadly no go as it requires GTK 3.22 (libratbag is present in the repos tough). So appimage would be awesome solution.

**Comment by Hjdskes** [comment] 2017-11-26 12:07
We would certainly welcome it (see also #93 and #5 for Snap and Flatpak issues), but someone else is going to have to do the work.

**Comment by whot** [comment] 2017-11-26 22:39
I forgot, do we have any reasons why piper can't run as flatpak now? It's just dbus and a file portal to the SVG files, nothing else should be necessary. The problem is that libratbag's dbus API is not yet stable so shipping piper as flatpack is more likely to confuse people when the dbus code explodes with API incompatibilities.

**Comment by Hjdskes** [comment] 2017-11-28 09:39
It may indeed be possible to flatpak Piper now. I'll open another issue to track this.

**Comment by probonopd** [comment] 2018-05-16 16:54
Apparently there is demand:

https://twitter.com/RuiCaridade83/status/996761582142197760

I'm happy to help the team to make an AppImage if the team wants to provide an officially-supported AppImage, and if the application can be built on Ubuntu trusty (because that's currently the oldest still-supported LTS release and is what I am targeting for the AppImages I am working on).

**Comment by probonopd** [comment] 2018-05-16 20:44
Miniconda is a version of Python that can run on multiple distributions. It might be a good idea to use that, because it is supposed to be isolated from the Python in the base system (Linux distribution). Here is a script that installs FreeCAD using Conda:
https://github.com/looooo/FreeCAD_Conda/blob/master/utils/appimage/freecad_app_image.sh

Would something along those lines be an option for populating the AppImage?

**Comment by whot** [comment] 2018-05-16 23:25
I don't know how AppImage works in detail, but the issues from #209 are at installation time and don't affect the runtime (even though it only shows up when you're running it). Presumably you can work around this during the AppImage build process?

**Comment by probonopd** [comment] 2018-05-17 05:33
The application needs a daemon running in the background?

**Comment by whot** [comment] 2018-05-17 06:35
yeah, ratbagd (provided by libratbag) is the dbus daemon that does all the work. Piper is just the frontend for the DBus interface

**Comment by probonopd** [comment] 2018-05-17 07:31
OK, then we'd need a startup script that starts the daemon, launches the GUI, and makes sure that the daemon gets killed once the GUI quits.

**Comment by whot** [comment] 2018-05-17 23:10
the daemon also needs to run as root (write access to /dev/hidraw) and requires access to udev which at last with flatpak isn't possible. Which is why we haven't packaged that as flatpaks yet. I suspect AppImage suffers from the same issues.

**Comment by probonopd** [comment] 2018-05-18 08:11
It doesn't. An AppImage is just a self-mounting filesystem inside which you can do what you as the application author want to do. There is no enforced sandboxing, although some users may choose to run AppImages inside sandboxes.

**Comment by whot** [comment] 2019-06-04 02:06
It's been a year since, let's close this. If you want to work on an AppImage, please feel free to submit a PR and we can review it. Keeping this bug open doesn't really provide any benefit at this point.

**Closed by whot** 2019-06-04 02:06 UTC
Labels: help wanted
