### ISSUE TITLE
"Buttons" and "LEDs" pages empty for G600

### ISSUE THREAD

**Issue by gerardlouw** [libratbag/piper#347] opened 2019-05-09 20:04 UTC
Libratbag/Piper: latest from [PPA](https://launchpad.net/~libratbag-piper/+archive/ubuntu/piper-libratbag-git)
Mouse: Logitech G600 (singing-gundi)
Distro: KDE neon (latest, Ubuntu 16.04-based)
Desktop environment: KDE
Output: [`ratbagtl singing-gundi info`](https://github.com/libratbag/piper/files/3163804/ratbagctl.txt)
Screenshots:
![Resolutions](https://user-images.githubusercontent.com/1428904/57483387-09bd0c00-72a7-11e9-9f0d-b2860adf6c16.png)
![Buttons](https://user-images.githubusercontent.com/1428904/57483395-0cb7fc80-72a7-11e9-9ed8-04fafb34e4f7.png)
![LEDs](https://user-images.githubusercontent.com/1428904/57483401-0f1a5680-72a7-11e9-82f1-c2de71a096eb.png)

**Comment by whot** [comment] 2019-05-09 22:37
>  Mouse: Logitech G600 (singing-gundi)

fwiw, the fake name is just assigned to have a guaranteed unique name, you can use a substring of the actual name, e.g. "G600".

Can you reproduce this with the libratbag and piper from git? There's been a recent set of issues with the PPA packages, so I'd rather have this confirmed with the real sources.

**Comment by gerardlouw** [comment] 2019-05-12 16:35
Confirmed that I'm getting the same behaviour using the latest git version of both `libratbag` and `piper`.

FYI I needed to install the following packages by trial and error to build these (I wasn't able to find a listing of dependencies). It might be useful to document them somewhere?

```
sudo apt install meson libudev-dev libevdev-dev libunistring-dev libsystemd-dev check valgrind swig # libratbag
sudo apt install python-gi-dev gettext
```

**Comment by gerardlouw** [comment] 2019-05-12 16:37
When running `piper` from a shell I see the following error logs, both using the git versions and the PPA versions:

```
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_piper.1000.crash'

Original exception was:
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
```

**Comment by gerardlouw** [comment] 2019-05-12 16:43
After finding [this answer](https://stackoverflow.com/questions/42279510/couldnt-find-foreign-struct-converter-for-cairo-context) I installed the package `python3-gi-cairo`, and now all three tabs render as expected, so it looks like this is a missing dependency.

**Comment by whot** [comment] 2019-05-21 22:13
yeah, this looks like a packaging issue, I'll refer to that PR you linked above. Thanks for finding the issue.

**Closed by whot** 2019-05-21 22:13 UTC

**Comment by muzena** [comment] 2019-06-19 01:03
@gerardlouw 
How do you install libratbag on Ubuntu 16.04 from this PPA, PPA dosen't support Ubuntu xenial? I was unable to install Piper on Ubuntu 16.04 due to python3.6 problem #66

**Comment by gerardlouw** [comment] 2019-06-25 09:09
Sorry that was an error, it's actually based on 18.04.
