### ISSUE TITLE
I'm trying open. Does not open.

### ISSUE THREAD

**Issue by Rodscaloppe** [libratbag/piper#661] opened 2021-07-22 21:34 UTC
**Information**
- `ratbagd` : 0.16
- Piper version: 0.5.1+git462-e117e87-202106222036~ubuntu20.04.1
- update: 22/07/2021
- Distribution: Ubuntu 20.04.2 LTS and Gnome 3.36.8
- Kernel version: `KERNEL VERSION HERE`

**Describe the bug**
I'm trying open. Does not open and crashed all my Desktop.

**Comment by Rodscaloppe** [comment] 2021-07-22 21:35
is there a problem with my computer?

**Comment by ocumo** [comment] 2021-07-25 11:50
Please see #664.
There is nothing wrong with your computer, nor did you do anything wrong.
The problem is a typo in the last piper installer.  That needs to be corrected by the developers, but in the mean time, you should be able to temporarily fix it (until there is a new, fixed installer version) as I explain in that bug report.

**Closed** 2021-07-28 05:18 UTC
Labels: bug
