### ISSUE TITLE
Bind Arbitrary Keys

### ISSUE THREAD

**Issue by Churchexe** [libratbag/piper#881] opened 2023-05-05 10:02 UTC
**Is your feature request related to a problem? Please describe.**
There are a substantial number of keys that can be handled and processed like expected but are not present on most keyboards, allowing them to be safely bound to shortcuts and other actions without using keyboard real-estate. Prime examples of these keys would be F12-20 which are on no keyboards that I am aware of, yet are perfectly valid keys that can be used to trigger shortcuts. 

**Describe the solution you'd like**
Ideally some method of binding any arbitrary key to a mouse button without having to physically press that key on your keyboard. In lieu of that though, even just a dropdown in the Macro Creator menu that lets you select from just F12-20 would be a massive help. (and let's be honest, most mice don't have more than 8 buttons that you'd want to rebind anyhow)

**Describe alternatives you've considered**
You could list F12-20 in the "Special Mapping" section, but I worry that would greatly bloat the menu and make it noticably more cumbersome to use. Another option is making a dedicated menu for binding abnormal keys, perhaps just below the "Send keystroke" menu.

**Comment by staticssleever668** [comment] 2023-05-05 10:34
NOTE: you can do this with ratbagctl - the command line interface for libratbag.
For example: `ratbagctl Glorious button 5 action set key KEY_F18` (On Glorious Model O it seems that you can bind F13-F18 only, if you try to set F19-F24, the mouse seems to send KEY_RESERVED instead).

**Comment by staticssleever668** [comment] 2023-05-05 10:35
I think this can be considered a duplicate of #567.

**Closed by staticssleever668** 2023-05-05 10:35 UTC
Labels: enhancement
