### ISSUE TITLE
Clearing out a resolution for Logitech G502 (setting back to "0 DPI")

### ISSUE THREAD

**Issue by moll** [libratbag/piper#297] opened 2019-02-02 17:31 UTC
Hey!

The G502 seems to work out of the box on Piper on Arch Linux. Thanks for the great work!
I noticed that the G502 seems to permit up to 5 resolution values per profile, some of which were left empty by default ("0 DPI") and therefore skipped when using the mouse's up-down resolution buttons. Once I touched those in Piper, however, I couldn't get them back to "0", only "50" at its lowest. Is that a bug in Piper or in libratbag?

Thanks!

PS. This with Piper v0.2.903.

**Comment by Hjdskes** [comment] 2019-02-02 17:33
Duplicate of #266, see that issue :) TL;DR is it just needs to be implemented.

**Closed by Hjdskes** 2019-02-02 17:33 UTC

**Comment by moll** [comment] 2019-02-02 17:47
Ah, I didn't realize "DPI profile" was the same thing that I was after. Thanks!

**Comment by Hjdskes** [comment] 2019-02-02 17:54
No worries!
