### ISSUE TITLE
Cannot find any devices for Logitech G502 Proteus Spectrum 

### ISSUE THREAD

**Issue by rudolfschmidt** [libratbag/piper#392] opened 2019-09-05 16:55 UTC
When I start my piper0.3-1 and my G502 is pluggedin I get devices not found error message.

![image](https://user-images.githubusercontent.com/1162911/64362377-b9fd1000-d00e-11e9-8cd5-3f683fa30679.png)

![image](https://user-images.githubusercontent.com/1162911/64362769-64753300-d00f-11e9-8e2e-25aed3b38b85.png)

![image](https://user-images.githubusercontent.com/1162911/64362800-72c34f00-d00f-11e9-9931-5e15c06c4d46.png)

**Comment by whot** [comment] 2019-09-06 05:45
does `ratbagctl list` find the device? If not, then the issue is in libratbag, not piper.

**Comment by rudolfschmidt** [comment] 2019-09-07 01:41
![image](https://user-images.githubusercontent.com/1162911/64468159-53b4e200-d121-11e9-8d9c-74496ce1e700.png)

**Comment by FFY00** [comment] 2019-09-07 10:15
Yes, this is related to libratbag.

Closing this is favor of https://github.com/libratbag/libratbag/issues/808.

**Closed by FFY00** 2019-09-07 10:15 UTC
