### ISSUE TITLE
Unassign buttons / Set action for button to nothing

### ISSUE THREAD

**Issue by paines** [libratbag/piper#498] opened 2020-04-06 19:31 UTC
So this is the only ttol which lets me change the behaviour of my forward / backward buttons. However, it seems to me at least, you HAVE to set a definitve action for a button. Right now I have set to to normal mouse click. Would it be possible that the pressed button does nothing , meaning unassign complete action from the button.

**Comment by stephanlachnit** [comment] 2020-04-11 23:20
Isn't that related to libratbag/libratbag#674 @FFY00?

**Comment by FFY00** [comment] 2020-04-11 23:23
Yes, that should be resolved.

**Comment by FFY00** [comment] 2020-04-14 15:58
#953 should fix things from the libratbag side, we still need to add support in piper.

**Comment by QazCetelic** [comment] 2020-06-11 10:48
Duplicate of #247

**Closed** 2022-10-15 09:38 UTC
Labels: enhancement
