### ISSUE TITLE
UI problem

### ISSUE THREAD

**Issue by benneti** [libratbag/piper#249] opened 2018-09-05 16:54 UTC
The UI seems wrong as the pointers do not point to the buttons (see screenshot).
![bildschirmfoto von 2018-09-05 16-57-42](https://user-images.githubusercontent.com/11725645/45108285-7c844f00-b13c-11e8-836c-11d1b5cd685c.png)

Some more details: logitech G403, Piper 0.2.901 from community repo in [arch](https://www.archlinux.org/packages/community/any/piper/)

Additional question, is it not possible to remap the buttons on the side for this model?

Finally thank you for providing a way to use all the features of a mouse in linux 

EDIT: maybe some more usefull infos:
lsusb
`Bus 002 Device 007: ID 046d:c083 Logitech, Inc. G403 Prodigy Gaming Mouse`

ratbagctl info event18
```
event18 - Logitech G403 Prodigy Gaming Mouse
               SVG: /usr/share/libratbag/gnome/logitech-g403.svg
      Capabilities: query-configuration, resolution, switchable-resolution, profile, disable-profile, led
 Number of Buttons: 6
    Number of Leds: 2
Number of Profiles: 1
Profile 0: (disabled) (active)
```

**Comment by benneti** [comment] 2018-09-05 19:47
this is the version I have: librsvg `2:2.44.2-1`

**Comment by whot** [comment] 2018-09-06 05:54
The buttons should be on the button panel, yes. This looks like a dupe of #233 though, closing.

**Closed by whot** 2018-09-06 05:54 UTC

**Comment by benneti** [comment] 2018-09-06 07:57
Oh sorry, I didn't see that one.
But is the button panel missing a separate bug?

**Comment by whot** [comment] 2018-09-10 07:09
No, not in your case. the capabilities listed by ratbagd don't include 'buttons' which means the device either doesn't have configurable buttons or libratbag doesn't know how to handle them. So piper is correct in not displaying the buttons page in this case.
