### ISSUE TITLE
No active profile error

### ISSUE THREAD

**Issue by hackedbellini** [libratbag/piper#239] opened 2018-08-24 16:02 UTC
When trying to run piper I got this error:
```
Running from source tree, using local files
No active profile. Please report this bug to the libratbag developers
Traceback (most recent call last):
  File "/home/hackedbellini/tmp/piper/piper/application.py", line 52, in do_activate
    window = Window(self._ratbag, application=self)
  File "/home/hackedbellini/tmp/piper/piper/window.py", line 67, in __init__
    self._present_mouse_perspective(ratbag.devices[0])
  File "/home/hackedbellini/tmp/piper/piper/window.py", line 150, in _present_mouse_perspective
    mouse_perspective.set_device(device)
  File "/home/hackedbellini/tmp/piper/piper/mouseperspective.py", line 96, in set_device
    self.label_profile.set_label(active_profile.name)
TypeError: Argument 1 does not allow None as a value
```
obs. Running locally (`./builddir/piper.devel`) in Debian Testing

**Comment by Hjdskes** [comment] 2018-08-24 19:42
What device do you own? What does ratbagctl tell you?

**Comment by hackedbellini** [comment] 2018-08-24 21:04
@Hjdskes 

```
➜  ~/t/piper git:(master) ratbagctl list-devices                                                                                                                                                                       hackedbellini@rathalos
event1:    Logitech G300s Optical Gaming Mouse
➜  ~/t/piper git:(master) ratbagctl show-device event1                                                                                                                                                                 hackedbellini@rathalos
event1 - Logitech G300s Optical Gaming Mouse
               SVG: logitech-g300.svg
      Capabilities: switchable-resolution, switchable-profile, query-configuration
Number of Profiles: 3
    Active Profile: 2```

**Comment by Hjdskes** [comment] 2018-08-24 21:39
Oke, so the device does have an active profile. If you can run Piper again and confirm that it still says there isn't an active profile, then we are somehow getting an empty profile list from ratbagd.

**Comment by hackedbellini** [comment] 2018-08-24 22:28
@Hjdskes same!

I added some prints and tried to check where the issue was coming from. Just discovered that [this line](https://github.com/libratbag/piper/blob/master/piper/ratbagd.py#L410) is returning `None` for all 3 devices created by [this line](https://github.com/libratbag/piper/blob/master/piper/ratbagd.py#L325).

Since `RagbagdDevice.active_profile` device iterates over the profiles and try to find the one that has `._active == True` it only find `Nones` and fails.

If you want me to do any testing/debugging just ask! I can handle python/gtk very well ;)

**Comment by phomes** [comment] 2018-08-25 06:31
Is this with libratbag from git?

**Comment by hackedbellini** [comment] 2018-08-25 12:06
@phomes I had those installed:
```
dpkg -l | grep ratbag                                                                                                                                                                      hackedbellini@rathalos
ii  libratbag-common                      0.9-5                                   all          configuration library for gaming mice - common files
ii  libratbag4:amd64                      0.9-5                                   amd64        configuration library for gaming mice
ii  ratbagd                               0.4-4                                   amd64        D-Bus daemon handling mouse configuration
```
After you said that, I upgraded `ragbabd` to the version in experimental. That removed the other 2 libraries, but upgraded `ratbagd` to `0.9`. Now piper is finally opening!

**Comment by hackedbellini** [comment] 2018-08-25 14:13
Maybe it should be documented in the `README` what is the minimum `ratbagd` version that you should have installed? If you tell me what it is I can create a PR adding that info

**Comment by whot** [comment] 2018-08-26 22:15
The DBus API itself hasn't changed in quite a while but the problem is we still have a fair few low-hanging fruit in ratbagd that needs fixing (like all the `None` index errors, etc.). Right now, the minimum version is unfortunately best specified as `git master`. I'll push out a ratbagd release this week though so at least that makes this bit easier.

**Comment by whot** [comment] 2018-08-29 01:02
AIUI this bug is fixed with latest libratbag? If so, closing, please re-open if I misunderstood this.

**Closed by whot** 2018-08-29 01:02 UTC

**Comment by hackedbellini** [comment] 2018-08-29 01:08
@whot yes it is fixed, but I still think that the minimum required version of `libratbag` should be documented in somewhere in the repository (e.g. in the README)
