### ISSUE TITLE
Direct media mappings while configuring mouse buttons

### ISSUE THREAD

**Issue by Netherquark** [libratbag/piper#683] opened 2021-10-01 04:33 UTC
**Is your feature request related to a problem? Please describe.**
There isn't a direct equivalent to the media mappings feature present in G Hub. The current compromise to this is setup macros for media controls in the DE, and then make the mouse button press activate that macro. Eg. Set up Ctrl + Shift + :arrow_right: to play next song in Gnome, and set up Piper so that a mouse's side button press triggers Ctrl + Shift + :arrow_right:. However, if you do happen to have a keyboard with media controls (eg my HP KM300F keyboard), you can directly map those same controls without having to go through the DE's settings and creating keyboard macros. This is what it looks like:
![image](https://user-images.githubusercontent.com/65618735/135565337-9f314af6-c308-4980-a09c-e5d364004443.png)

**Describe the solution you'd like**
It would be amazing if we could directly select the NEXTSONG and PLAYPAUSE macros while configuring button mapping. I'd reckon it won't be that hard either, considering most of the Logitech mice this software works for, also show up as keyboards for their special functions (atleast in G Hub). 

**Describe alternatives you've considered**
The DE macro method is a less convenient way to accomplish the same, but while also losing out on one keyboard mapping.

Note: the aforementioned HP KM300F does not have any software to install, on either Windows, Linux or macOS, so the NEXTSONG and PLAYPAUSE key events are probably low level, basic commands.

**Comment by Ryhon0** [comment] 2022-03-11 12:45
Also missing volume up/down and mute keys. I was able to map music playback keys with my keyboard, but it doesn't have volume control keys

**Comment by Ryhon0** [comment] 2022-03-11 16:31
If anyone's interested, I've made a fork with a basic implementation of it, it lists media keys and when selected, the button is set to a macro with a press and release of selected key. No translations, button labels show as macros, instead of media key names, mute button doesn't have a string for macros. A proper implementation should probably have a dropdown menu with all possible keys.
<details>
<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/21126698/157907817-aa33e37b-bf21-4767-8fab-012223dc0575.png)
![image](https://user-images.githubusercontent.com/21126698/157907959-c5d5e1f5-8fa6-4ae2-ab77-f234d3fda6f3.png)

</details>

**Comment by ShugarSkull** [comment] 2023-01-12 21:07
@Ryhon0 Do you plan to make this a pull request ?

**Comment by Ryhon0** [comment] 2023-01-12 21:19
Nope. My implementation is kinda hacky, it'd probably be better if some contributor implemented this in the main branch.
Also I just realized I did not link to the repo, whoops!
https://github.com/Ryhon0/piper

**Comment by LarissaGuder** [comment] 2023-02-14 02:21
Is there any chance that this feature will be implemented?

**Comment by staticssleever668** [comment] 2023-03-06 19:47
For now you can do this with some mice with ratbagctl:
```
ratbagctl <device name> button 5 action set key KEY_VOLUMEUP
ratbagctl <device name> button 5 action set key KEY_PLAYPAUSE
```

**Comment by staticssleever668** [comment] 2023-05-05 10:39
Seems like a duplicate of #567.

**Closed by staticssleever668** 2023-05-05 10:39 UTC
Labels: enhancement
