### ISSUE TITLE
Support for Logitech MX1000 Laser Cordless Mouse ???

### ISSUE THREAD

**Issue by DarthRidar** [libratbag/piper#926] opened 2023-12-23 08:43 UTC
Can you integrate the Logitech MX1000 Laser Cordless Mouse? Yes, it's an old mouse. But I like using them. Best regards

**Comment by staticssleever668** [comment] 2023-12-26 18:33
Closing as duplicate of https://github.com/libratbag/libratbag/issues/1528. Please answer there. :)

**Closed by staticssleever668** 2023-12-26 18:34 UTC
Labels: enhancement
