### ISSUE TITLE
Only the Logo LED can be configured on Logitech G903 (not the DPI LED's)

### ISSUE THREAD

**Issue by ChausseBenjamin** [libratbag/piper#310] opened 2019-02-28 04:50 UTC
The title is pretty self-explanatory...
Consider this something that isn't urgent, but more noteworthy...

**Comment by bentiss** [comment] 2019-02-28 07:50
That is the intended behaviour. The DPI LED *could* be configured with a few caveats:
- you'll lose the default behaviour (LEDs changing with the DPI or profile)
- the setting will not be retained by the HW itself.

Given those reasons, it's a design choice in Piper to not expose the DPI LED IIRC.

Closing for the reasons above

**Closed by bentiss** 2019-02-28 07:50 UTC
