### ISSUE TITLE
DEB Package for Ubuntu 22.04 fails to install properly

### ISSUE THREAD

**Issue by drivera-armedia** [libratbag/piper#758] opened 2022-06-22 17:32 UTC
**Information**
- Piper version: piper_0.7+git490-7f9834c~ubuntu22.04.1_all.deb
- Distribution: Ubuntu 22.04

**Describe the bug**
The DEB package installation complains that the postinst hook fails. The installation includes the **_directory_** /usr/lib/python3/dist-packages/piper, but the postinst script attempts to create a link that would conflict with that directory.

A cleaner approach would be a script that checks to see if the directory entry exists first, and if not then attempts to create the link, vs. simply checking to see if the target is a link (using -L) as the means of validation.

**To Reproduce**

1. Add the Piper PPA to Ubuntu via `add-apt-repository ppa:libratbag-piper/piper-libratbag-git`
2. Run the `apt-get update` command to update the repository listings
3. Install piper via `apt-get install piper`
4. See the error `Errors were encountered while processing: piper`

**Comment by dreamcat4** [comment] 2022-06-25 09:17
would be great to see a fix... can't be that difficult surely?

**Comment by drivera-armedia** [comment] 2022-06-25 13:36
Sure! Just not sure how to contribute it 🙁

--

Diego Rivera
Application Architect
Cell: +1 (404) 287-0580
***@***.***
￼

On Jun 25, 2022 03:17, Dreamcat4 ***@***.***> wrote:

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


would be great to see a fix... can't be that difficult surely?

**Comment by TimLavelle** [comment] 2022-07-02 01:02
I have the same issue with the PPA as well, sym link error
```
Piper symlink does not exists, creating symlink for python 3.10
ln: failed to create symbolic link '/usr/lib/python3/dist-packages/piper': File exists
dpkg: error processing package piper (--configure):
 installed piper package post-installation script subprocess returned error exit status 1
```

**Comment by dreamcat4** [comment] 2022-07-20 15:45
ok, the problem is in `piper.postinst` here:

[piper_0.7+git490-7f9834c~ubuntu22.10.1.tar.gz](https://launchpad.net/~libratbag-piper/+archive/ubuntu/piper-libratbag-git/+sourcefiles/piper/0.7+git490-7f9834c~ubuntu22.10.1/piper_0.7+git490-7f9834c~ubuntu22.10.1.tar.gz) (267.8 KiB)



```sh
#!/bin/sh
set -e

#PYTHON_VERSION=$(python3 -V | tail -c 7 | sed 's/ //' | cut -c-4 | sed -e 's/^[ \t]*//')
PYTHON_VERSION=$(python3 -c 'import sys; print(".".join(map(str, sys.version_info[0:2])))')

# Fix python dependencies, make python 3 symlink

if [ -L "/usr/lib/python3/dist-packages/piper" ]; then
    echo "Piper symlink exists for python $PYTHON_VERSION, nothing to do"
    echo "Continuing to start service"
else
    echo "Piper symlink does not exists, creating symlink for python $PYTHON_VERSION"
    ln -s /usr/lib/python$PYTHON_VERSION/site-packages/piper /usr/lib/python3/dist-packages
fi
```

```sh
Publishing details

    [Built](https://launchpad.net/~libratbag-piper/+archive/ubuntu/piper-libratbag-git/+recipebuild/3383296) by recipe [piper](https://code.launchpad.net/~libratbag-piper/+recipe/piper) for [gogo](https://launchpad.net/~trebelnik-stefina)
    Published on 2022-06-22

Changelog

piper (0.7+git490-7f9834c~ubuntu22.10.1) kinetic; urgency=low

  * Auto build.

 -- gogo <[trebelnik2@gmail.com](https://launchpad.net/~trebelnik-stefina)>  Wed, 22 Jun 2022 22:35:03 +0000
```

@muzena can you fix this please? The script is bad

**Comment by dreamcat4** [comment] 2022-07-20 15:48
The test is for symlink, but the pkg installed a directory

```sh
ll /usr/lib/python3/dist-packages | grep piper
drwxr-xr-x  2 root root 4.0K Jul 20 16:41 piper/
```
you can do;

```sh
if [ -e "/usr/lib/python3/dist-packages/piper" ]; then
```

instead of `-L` and re-upload. thanks

**Comment by muzena** [comment] 2022-07-20 18:28
I will check this.

**Comment by muzena** [comment] 2022-07-21 05:53
Problem is in older releases of Ubuntu, Piper is installed in path:
/usr/lib/python3.8/dist-packages/piper
or
/usr/lib/python3.7/dist-packages/piper
or
/usr/lib/python3.6/dist-packages/piper
etc....
So symlinking is necessary  to '/usr/lib/python3/dist-packages/piper' path in older releases.

Now it seems they fixed this problem/bug.

**Comment by dreamcat4** [comment] 2022-07-21 06:36
> Now it seems they fixed this problem/bug.

Hello, I am currently on 22.04 (after upgrade from earlier versions of ubuntu).

* Have tried removing piper and re-installing
* Bug still occurs
* So how can it be fixed on the user side?
* Also why in the script does it say BOT `.../dist-packages/` and also `.../site-packages/` ?

**Comment by muzena** [comment] 2022-07-21 07:08
This path problem was in Python packaging

**Comment by muzena** [comment] 2022-07-21 07:35
@dreamcat4 
Try now upgrade or install.

**Comment by dreamcat4** [comment] 2022-07-21 07:52
@muzena it worked! thank you

```sh
θ68° [id:~] $ sudo apt install piper
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be upgraded:
  piper
1 to upgrade, 0 to newly install, 0 to remove and 14 not to upgrade.
1 not fully installed or removed.
Need to get 190 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://ppa.launchpad.net/libratbag-piper/piper-libratbag-git/ubuntu jammy/main amd64 piper all 0.7+git490-7f9834c-202207210700~ubuntu22.04.1 [190 kB]
Fetched 190 kB in 1s (148 kB/s)                      
(Reading database ... 1354183 files and directories currently installed.)
Preparing to unpack .../piper_0.7+git490-7f9834c-202207210700~ubuntu22.04.1_all.deb ...
Unpacking piper (0.7+git490-7f9834c-202207210700~ubuntu22.04.1) over (0.7+git490-7f9834c~ubuntu22.04.1) ...
Setting up piper (0.7+git490-7f9834c-202207210700~ubuntu22.04.1) ...
$
```

**Comment by whot** [comment] 2022-08-15 05:39
Looks like this was fixed in the PPA, let's close this issue! thanks @muzena

**Closed by whot** 2022-08-15 05:39 UTC
Labels: bug
